<a href="https://colab.research.google.com/github/piyu-data-analyst/Data-analysis/blob/main/LogisticRegressionFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import seaborn as sns
import pandas as pd

In [2]:
df = sns.load_dataset("iris")
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [5]:
df.rename(columns={'old_name': 'new_name'}, inplace=True)

In [6]:
#df.info()      # info about columns, types, missing values
df.describe()  # summary statistics for numerical columns
df.shape       # number of rows and columns
df.columns     # column names
df.dtypes      # data types of columns

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [23]:
# # # Drop rows with missing values
# df.dropna(inplace=True)

# # # Drop columns with missing values
# df.dropna(axis=1, inplace=True)

# # # Fill missing values
# df['column'] = df['column'].fillna(0)          # replace with constant
# # df['column'] = df['column'].fillna(df['column'].mean())  # replace with mean
# # df['column'] = df['column'].fillna(df['column'].median())
# # df['column'] = df['column'].fillna(df['column'].mode()[0])

In [8]:
# # # # Manual mapping
# # #df['species'] = df['species'].map({'setosa':0, 'versicolor':1, 'virginica':2})
# # # # Label Encoding
# # from sklearn.preprocessing import LabelEncoder
# # le = LabelEncoder()
# # df=le.fit_transform(df['species'])


# #print(le.classes_)

# # # # One-hot encoding
# df = pd.get_dummies(df, columns=['species'])  # creates new 0/1 columns
# df

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [11]:
df['species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [12]:
X = df.drop("species", axis=1)
y = df["species"]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [15]:
y_pred = model.predict(X_test)

In [16]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [17]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [18]:
new_flower = [[5.1, 3.5, 1.4, 0.2]]
prediction = model.predict(new_flower)

# flower_names = ['setosa', 'versicolor', 'virginica']
# print("Predicted species:", flower_names[prediction[0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [19]:
label_mapping = {0: 'setosa', 1: 'versicolor', 2: 'virginica'}

# Convert predicted numbers to names
pred_labels = [label_mapping[i] for i in y_pred]

# Convert actual numbers to names
actual_labels = [label_mapping[i] for i in y_test]

In [20]:
# Make X_test a DataFrame if needed
X_test_df = pd.DataFrame(X_test, columns=X.columns)

# Add predicted and actual labels
X_test_df['predicted_species'] = pred_labels
X_test_df['actual_species'] = actual_labels

print(X_test_df)

     sepal_length  sepal_width  petal_length  petal_width predicted_species  \
73            6.1          2.8           4.7          1.2        versicolor
18            5.7          3.8           1.7          0.3            setosa
118           7.7          2.6           6.9          2.3         virginica
78            6.0          2.9           4.5          1.5        versicolor
76            6.8          2.8           4.8          1.4        versicolor
31            5.4          3.4           1.5          0.4            setosa
64            5.6          2.9           3.6          1.3        versicolor
141           6.9          3.1           5.1          2.3         virginica
68            6.2          2.2           4.5          1.5        versicolor
82            5.8          2.7           3.9          1.2        versicolor
110           6.5          3.2           5.1          2.0         virginica
12            4.8          3.0           1.4          0.1            setosa
36            5.5          3.5           1.3          0.2            setosa
9             4.9          3.1           1.5          0.1            setosa
19            5.1          3.8           1.5          0.3            setosa
56            6.3          3.3           4.7          1.6        versicolor
104           6.5          3.0           5.8          2.2         virginica
69            5.6          2.5           3.9          1.1        versicolor
55            5.7          2.8           4.5          1.3        versicolor
132           6.4          2.8           5.6          2.2         virginica
29            4.7          3.2           1.6          0.2            setosa
127           6.1          3.0           4.9          1.8         virginica
26            5.0          3.4           1.6          0.4            setosa
128           6.4          2.8           5.6          2.1         virginica
131           7.9          3.8           6.4          2.0         virginica
145           6.7          3.0           5.2          2.3         virginica
108           6.7          2.5           5.8          1.8         virginica
143           6.8          3.2           5.9          2.3         virginica
45            4.8          3.0           1.4          0.3            setosa
30            4.8          3.1           1.6          0.2            setosa

    actual_species
73      versicolor
18          setosa
118      virginica
78      versicolor
76      versicolor
31          setosa
64      versicolor
141      virginica
68      versicolor
82      versicolor
110      virginica
12          setosa
36          setosa
9           setosa
19          setosa
56      versicolor
104      virginica
69      versicolor
55      versicolor
132      virginica
29          setosa
127      virginica
26          setosa
128      virginica
131      virginica
145      virginica
108      virginica
143      virginica
45          setosa
30          setosa

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]